
# 👩‍💻 Data Preparation: Encoding Categorical Variables for Salary Prediction

## 📋 Overview
In this lab, you'll learn how to transform categorical data into numerical form - a crucial step in preparing data for machine learning models. You'll work with a dataset containing information about individuals' salaries, education levels, and occupations. By applying appropriate encoding techniques to these categorical variables, you'll prepare the data for a salary prediction model while maintaining the underlying relationships within the data.

## 🎯 Learning Outcomes
By the end of this lab, you will be able to:

- Identify which categorical variables need transformation and select appropriate encoding techniques

- Implement One-Hot Encoding for nominal categorical variables using scikit-learn

- Apply Label Encoding for ordinal categorical variables

- Integrate encoded variables back into a dataset for machine learning preparation

## 🚀 Starting Point

In [1]:
# Starter code - imports and data loading
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Load the dataset
data = pd.read_csv('Salary Data.csv')
print(data.shape)
data.head(2)

(375, 6)

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0

## Task 1: Dataset Exploration
**Context:** Before we can process categorical data, we need to understand the structure of our dataset and identify which variables need encoding.

**Steps:**

1. Use the `head()` method to view the first few rows of the dataset
 - This will help you identify the columns present in the dataset
 - Look for categorical variables like job titles and education levels

2. Use the `describe()` method to get summary statistics for numerical columns
  - Pay attention to which columns are included or excluded from this summary
  - Columns not included are likely categorical and will need encoding

3. Examine the unique values in each categorical column

  - Use `data['column_name'].unique()` to see the distinct categories
  - Note whether categories have a natural order (ordinal) or not (nominal)

In [3]:
# Your code for dataset exploration

display(data.head())
display(data.describe().T)
print()
print(data['Job Title'].unique())

print()
print("="*100)
print()

print(data['Education Level'].unique())

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

,count,mean,std,min,25%,50%,75%,max
Age,373.0,37.431635,7.069073,23.0,31.0,36.0,44.0,53.0
Years of Experience,373.0,10.030831,6.557007,0.0,4.0,9.0,15.0,25.0
Salary,373.0,100577.345845,48240.013482,350.0,55000.0,95000.0,140000.0,250000.0

['Software Engineer' 'Data Analyst' 'Senior Manager' 'Sales Associate'
 'Director' 'Marketing Analyst' 'Product Manager' 'Sales Manager'
 'Marketing Coordinator' 'Senior Scientist' 'Software Developer'
 'HR Manager' 'Financial Analyst' 'Project Manager' 'Customer Service Rep'
 'Operations Manager' 'Marketing Manager' 'Senior Engineer'
 'Data Entry Clerk' 'Sales Director' 'Business Analyst' 'VP of Operations'
 'IT Support' 'Recruiter' 'Financial Manager' 'Social Media Specialist'
 'Software Manager' 'Junior Developer' 'Senior Consultant'
 'Product Designer' 'CEO' 'Accountant' 'Data Scientist'
 'Marketing Specialist' 'Technical Writer' 'HR Generalist'
 'Project Engineer' 'Customer Success Rep' 'Sales Executive' 'UX Designer'
 'Operations Director' 'Network Engineer' 'Administrative Assistant'
 'Strategy Consultant' 'Copywriter' 'Account Manager'
 'Director of Marketing' 'Help Desk Analyst' 'Customer Service Manager'
 'Business Intelligence Analyst' 'Event Coordinator' 'VP of Finance'
 'Graphic Designer' 'UX Researcher' 'Social Media Manager'
 'Director of Operations' 'Senior Data Scientist' 'Junior Accountant'
 'Digital Marketing Manager' 'IT Manager'
 'Customer Service Representative' 'Business Development Manager'
 'Senior Financial Analyst' 'Web Developer' 'Research Director'
 'Technical Support Specialist' 'Creative Director'
 'Senior Software Engineer' 'Human Resources Director'
 'Content Marketing Manager' 'Technical Recruiter' 'Sales Representative'
 'Chief Technology Officer' 'Junior Designer' 'Financial Advisor'
 'Junior Account Manager' 'Senior Project Manager' 'Principal Scientist'
 'Supply Chain Manager' 'Senior Marketing Manager' 'Training Specialist'
 'Research Scientist' 'Junior Software Developer'
 'Public Relations Manager' 'Operations Analyst'
 'Product Marketing Manager' 'Senior HR Manager' 'Junior Web Developer'
 'Senior Project Coordinator' 'Chief Data Officer'
 'Digital Content Producer' 'IT Support Specialist'
 'Senior Marketing Analyst' 'Customer Success Manager'
 'Senior Graphic Designer' 'Software Project Manager'
 'Supply Chain Analyst' 'Senior Business Analyst'
 'Junior Marketing Analyst' 'Office Manager' 'Principal Engineer'
 'Junior HR Generalist' 'Senior Product Manager'
 'Junior Operations Analyst' 'Senior HR Generalist'
 'Sales Operations Manager' 'Senior Software Developer'
 'Junior Web Designer' 'Senior Training Specialist'
 'Senior Research Scientist' 'Junior Sales Representative'
 'Junior Marketing Manager' 'Junior Data Analyst'
 'Senior Product Marketing Manager' 'Junior Business Analyst'
 'Senior Sales Manager' 'Junior Marketing Specialist'
 'Junior Project Manager' 'Senior Accountant' 'Director of Sales'
 'Junior Recruiter' 'Senior Business Development Manager'
 'Senior Product Designer' 'Junior Customer Support Specialist'
 'Senior IT Support Specialist' 'Junior Financial Analyst'
 'Senior Operations Manager' 'Director of Human Resources'
 'Junior Software Engineer' 'Senior Sales Representative'
 'Director of Product Management' 'Junior Copywriter'
 'Senior Marketing Coordinator' 'Senior Human Resources Manager'
 'Junior Business Development Associate' 'Senior Account Manager'
 'Senior Researcher' 'Junior HR Coordinator' 'Director of Finance'
 'Junior Marketing Coordinator' nan 'Junior Data Scientist'
 'Senior Operations Analyst' 'Senior Human Resources Coordinator'
 'Senior UX Designer' 'Junior Product Manager'
 'Senior Marketing Specialist' 'Senior IT Project Manager'
 'Senior Quality Assurance Analyst' 'Director of Sales and Marketing'
 'Senior Account Executive' 'Director of Business Development'
 'Junior Social Media Manager' 'Senior Human Resources Specialist'
 'Senior Data Analyst' 'Director of Human Capital'
 'Junior Advertising Coordinator' 'Junior UX Designer'
 'Senior Marketing Director' 'Senior IT Consultant'
 'Senior Financial Advisor' 'Junior Business Operations Analyst'
 'Junior Social Media Specialist' 'Senior Product Development Manager'
 'Junior Operations Manager' 'Senior Software Architect'
 'Junior Research Scientist' 'Senior Financial Manager'
 'Senior HR Specialist' 'Senior Data Engineer'
 'Junior Operations Coordinator' 'Director of HR'
 'Senior Operations Coordinator' 'Junior Financial Advisor'
 'Director of Engineering']

====================================================================================================

["Bachelor's" "Master's" 'PhD' nan]

💡 **Tip:** Pay special attention to the data types returned by `data.info()` - columns with 'object' or 'string' types typically contain categorical data.

⚙️ **Test Your Work:**

- Your output should show that the dataset contains categorical columns including 'Job Title' and 'Education Level'
- You should be able to identify which columns need encoding for machine learning use

## Task 2: Select Encoding Techniques
**Context:** Different types of categorical data require different encoding approaches. In this task, you'll determine which encoding technique is best for each categorical variable.

**Steps:**

1. Identify nominal categorical variables (no inherent order)

 - Look at 'Job Title' - does one occupation inherently rank above another?
 - Consider whether One-Hot Encoding would be appropriate for this variable

2. Identify ordinal categorical variables (have a natural order)

 - Examine 'Education Level' - do the values have a natural progression?
 - Consider whether Label Encoding would preserve the ordinal relationship

In [ ]:
# Your code for identifying variable types and selecting encoding techniques

💡 **Tip:** One-Hot Encoding creates new binary columns for each category, while Label Encoding assigns a single numeric value to each category. Choose based on whether the relationship between categories matters.

⚙️ **Test Your Work:**

- You should have clearly identified 'Job Title' as a nominal variable suitable for One-Hot Encoding
- You should have identified 'Education Level' as an ordinal variable suitable for Label Encoding

## Task 3: Apply One-Hot Encoding
**Context:** One-Hot Encoding transforms a categorical variable into multiple binary columns, one for each category. This prevents the model from assuming ordinal relationships between categories.

**Steps:**

1. Import and initialize the OneHotEncoder

 - Set `sparse_output=False` to get a dense array rather than a sparse matrix

2. Apply the encoder to the 'Job Title' column

 - Use `fit_transform()` on the column reshaped as a 2D array
 - Note that OneHotEncoder expects a 2D array input, so use double brackets: `[['column_name']]`

3. Convert the encoded array to a DataFrame with appropriate column names

 - Use `encoder.get_feature_names_out()` to generate the column names
 - Create a DataFrame with these names and the encoded values

In [4]:
# Your code for One-Hot Encoding

encoder = OneHotEncoder(sparse=False)
occupation_encoded = encoder.fit_transform(data[['Job Title']])
occupation_encoded_df = pd.DataFrame(occupation_encoded, 
                                    columns=encoder.get_feature_names_out(['Job Title']))

💡 **Tip:** Check the shape of your output to ensure you have the expected number of new columns (one for each unique job title).

⚙️ **Test Your Work:**

- Your output should include new binary columns for each unique job title
- Each row should have a 1 in exactly one of the job title columns and 0s elsewhere

## Task 4: Apply Label Encoding
**Context:** Label Encoding converts categorical values into numeric values while preserving the ordinal relationship between categories.

**Steps:**

1. Import and initialize the LabelEncoder

2. Apply the encoder to the 'Education Level' column

 - Use `fit_transform()` directly on the column
 - Add the result as a new column in your DataFrame

3. Confirm the mapping between original values and encoded values

 - Use `label_encoder.classes_` to see the original categories
 - The index of each category in this array corresponds to its encoded value

In [5]:
# Your code for Label Encoding

label_encoder = LabelEncoder()
data['Education_Level_Encoded'] = label_encoder.fit_transform(data['Education Level'])
print("Original education levels:", label_encoder.classes_)
print("Encoded education levels:", {edu: idx for idx, edu in enumerate(label_encoder.classes_)})

Original education levels: ["Bachelor's" "Master's" 'PhD' nan]
Encoded education levels: {"Bachelor's": 0, "Master's": 1, 'PhD': 2, nan: 3}

💡 **Tip:** If the order of your categories matters (e.g., 'High School' < 'Bachelor' < 'Master'), you may need to manually specify this order rather than letting LabelEncoder decide automatically.

⚙️ **Test Your Work:**

- You should have a new column like 'Education_Level_Encoded' containing numeric values
- Higher education levels should generally have higher encoded values

## Task 5: Prepare Data for Modeling
**Context:** Now that we've encoded our categorical variables, we need to integrate them into a final dataset ready for machine learning.

**Steps:**

1. Drop the original categorical columns from the dataset

 - These are no longer needed since we have encoded versions

2. Concatenate the original numeric columns with the encoded categorical columns

 - Use `pd.concat()` to join DataFrames along the column axis (axis=1)

3. Verify that the final dataset contains all necessary features in appropriate format

 - Check that all categorical data has been properly encoded
 - Ensure there are no missing values

In [6]:
# Your code for integrating encoded data

data_encoded = pd.concat([data.drop(['Job Title', 'Education Level'], axis=1), 
                         occupation_encoded_df], axis=1)
data_encoded.head()

,Age,Gender,Years of Experience,Salary,Education_Level_Encoded,Job Title_Account Manager,Job Title_Accountant,Job Title_Administrative Assistant,Job Title_Business Analyst,Job Title_Business Development Manager,...,Job Title_Technical Recruiter,Job Title_Technical Support Specialist,Job Title_Technical Writer,Job Title_Training Specialist,Job Title_UX Designer,Job Title_UX Researcher,Job Title_VP of Finance,Job Title_VP of Operations,Job Title_Web Developer,Job Title_nan
0,32.0,Male,5.0,90000.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,28.0,Female,3.0,65000.0,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,45.0,Male,15.0,150000.0,2,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,36.0,Female,7.0,60000.0,0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,52.0,Male,20.0,200000.0,1,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

💡 **Tip:** Always check your final dataset shape to confirm you have the expected number of rows and columns after joining.

⚙️ **Test Your Work:**

- Your final DataFrame should no longer contain string-based categorical columns
- The row count should match your original dataset
- The column count should be greater than the original due to one-hot encoding

## ✅ Success Checklist

- Successfully loaded and explored the salary dataset
- Identified which variables require encoding and selected appropriate techniques
- Applied One-Hot Encoding to the 'Job Title' variable
- Applied Label Encoding to the 'Education Level' variable
- Created a final dataset with all categorical variables properly encoded
- Documented the reasoning behind encoding choices
- Program runs without errors

## 🔍 Common Issues & Solutions

**Problem:** One-Hot Encoding creates too many columns when there are many unique categories.

**Solution:** Consider grouping similar categories together before encoding, or use dimensionality reduction techniques afterward.

**Problem:** LabelEncoder assigns numbers based on alphabetical order, which may not match the logical ordering.

**Solution:** Create a custom mapping dictionary to assign numbers in the correct order, or use OrdinalEncoder with specified category orders.

**Problem:** Missing values in categorical columns cause errors during encoding.

**Solution:** Handle missing values before encoding, either by filling them in or creating a separate category for missing values.

## 🔑 Key Points
- The choice of encoding technique depends on the nature of the categorical variable and its relationship to the target variable
- One-Hot Encoding preserves the lack of order in nominal variables but increases dimensionality
- Label Encoding is efficient for ordinal variables but can mislead models with non-ordinal data
- Proper encoding is essential for machine learning models to effectively use categorical information

## 💻 Exemplar Solution
After completing this activity (or if you get stuck!), take a moment to review the exemplar solution. This sample solution can offer insights into different techniques and approaches.
Reflect on what you can learn from the exemplar solution to improve your coding skills.
Remember, multiple solutions can exist for some problems; the goal is to learn and grow as a programmer by exploring various approaches.
Use the exemplar solution as a learning tool to enhance your understanding and refine your approach to coding challenges.

<details>

<summary><strong>Click HERE to see an exemplar solution</strong></summary>    
    
```python
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Load the dataset
data = pd.read_csv('Salary Data.csv')

# Task 1: Dataset Exploration
print(data.head())
print(data.describe())
print(data['Job Title'].unique())
print(data['Education Level'].unique())

# Task 2: Select Encoding Technique
# (This is a decision point based on analysis)

# Task 3: Apply One-Hot Encoding
encoder = OneHotEncoder(sparse=False)
occupation_encoded = encoder.fit_transform(data[['Job Title']])
occupation_encoded_df = pd.DataFrame(occupation_encoded, 
                                    columns=encoder.get_feature_names_out(['Job Title']))

# Task 4: Apply Label Encoding
label_encoder = LabelEncoder()
data['Education_Level_Encoded'] = label_encoder.fit_transform(data['Education Level'])
print("Original education levels:", label_encoder.classes_)
print("Encoded education levels:", {edu: idx for idx, edu in enumerate(label_encoder.classes_)})

# Task 5: Prepare Data for Modeling
data_encoded = pd.concat([data.drop(['Job Title', 'Education Level'], axis=1), 
                         occupation_encoded_df], axis=1)
print(data_encoded.head())

# Reflection
# Note: provide your own reflection on how encoding choices
# impact model development and performance
    
       
```